/**
 * Mock leads for demo purposes.
 *
 * MOCK_LEADS_CLIENT — Demo client account (painting equipment rental).
 *
 * Used as fallback when no real leads exist in the database.
 * Super admin (ODuo) always sees real data — no mock fallback.
 */

function daysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(Math.floor(Math.random() * 10) + 8, Math.floor(Math.random() * 60));
  return d.toISOString();
}

// ---------------------------------------------------------------------------
// Demo Client — Painting equipment rental company
// ---------------------------------------------------------------------------
export const MOCK_LEADS_CLIENT = [
  {
    id: "mock-cli-001",
    name: "Carlos Eduardo Silva",
    phone: "5511987651111",
    status: "new",
    conversion_value: null,
    lead_score: 47,
    interest_tags: ["Andaime Fachadeiro"],
    origin: "whatsapp",
    created_at: daysAgo(0),
    pipeline_status: "ia_atendendo",
    ai_summary: "Cliente perguntou sobre locação de andaime fachadeiro para pintura de prédio residencial de 6 andares. Precisa por 20 dias.",
    estimated_value: 4800,
    last_contact_at: daysAgo(0),
    conversation_id: null,
  },
  {
    id: "mock-cli-002",
    name: "Ana Paula Oliveira",
    phone: "5511976542222",
    status: "new",
    conversion_value: null,
    lead_score: 60,
    interest_tags: ["Pulverizador Airless", "Compressor para Pintura"],
    origin: "organic",
    created_at: daysAgo(0),
    pipeline_status: "ia_atendendo",
    ai_summary: "Interessada em pulverizador airless e compressor para pintura de galpão industrial. Área de 2.000m².",
    estimated_value: 6500,
    last_contact_at: daysAgo(0),
    conversation_id: null,
  },
  {
    id: "mock-cli-003",
    name: "Roberto Nascimento",
    phone: "5511965433333",
    status: "new",
    conversion_value: null,
    lead_score: 35,
    interest_tags: ["Lixadeira de Parede"],
    origin: "whatsapp",
    created_at: daysAgo(1),
    pipeline_status: "ia_atendendo",
    ai_summary: "Pediu orçamento de lixadeira de parede elétrica para preparação de superfície antes da pintura. Obra pequena, ainda avaliando.",
    estimated_value: 1800,
    last_contact_at: daysAgo(1),
    conversation_id: null,
  },
  {
    id: "mock-cli-004",
    name: "Fernanda Araújo",
    phone: "5511954324444",
    status: "new",
    conversion_value: null,
    lead_score: 52,
    interest_tags: ["Plataforma de Pintura", "Escada Extensível"],
    origin: "campaign",
    created_at: daysAgo(1),
    pipeline_status: "ia_atendendo",
    ai_summary: "Veio pela campanha do Instagram. Quer plataforma de pintura e escada extensível para reforma de casa. Prazo de 10 dias.",
    estimated_value: 3200,
    last_contact_at: daysAgo(0),
    conversation_id: null,
  },
  {
    id: "mock-cli-005",
    name: "Marcos Antônio Pereira",
    phone: "5511943215555",
    status: "qualified",
    conversion_value: null,
    lead_score: 73,
    interest_tags: ["Andaime Fachadeiro", "Pulverizador Airless"],
    origin: "whatsapp",
    created_at: daysAgo(2),
    pipeline_status: "qualificado",
    ai_summary: "Empresa de pintura predial precisa de andaime fachadeiro completo e pulverizador airless para projeto de condomínio. Prazo de 45 dias. Decisor confirmado.",
    estimated_value: 12000,
    last_contact_at: daysAgo(1),
    conversation_id: null,
  },
  {
    id: "mock-cli-006",
    name: "Juliana Monteiro",
    phone: "5511932106666",
    status: "qualified",
    conversion_value: null,
    lead_score: 66,
    interest_tags: ["Pistola de Pintura", "Compressor para Pintura"],
    origin: "organic",
    created_at: daysAgo(2),
    pipeline_status: "qualificado",
    ai_summary: "Pintora autônoma. Precisa de pistola de pintura HVLP e compressor para serviço em escritório comercial. Orçamento aprovado pelo contratante.",
    estimated_value: 2800,
    last_contact_at: daysAgo(1),
    conversation_id: null,
  },
  {
    id: "mock-cli-007",
    name: "Ricardo de Almeida",
    phone: "5511921097777",
    status: "qualified",
    conversion_value: null,
    lead_score: 81,
    interest_tags: ["Andaime Fachadeiro", "Rolo de Pintura Industrial"],
    origin: "whatsapp",
    created_at: daysAgo(3),
    pipeline_status: "transferido",
    ai_summary: "Construtora com obra de pintura de fachada de shopping. Precisa de andaime fachadeiro de grande porte e rolos industriais. Valor alto, transferido para consultor.",
    estimated_value: 18500,
    last_contact_at: daysAgo(0),
    conversation_id: null,
  },
  {
    id: "mock-cli-008",
    name: "Patrícia Gomes",
    phone: "5511910988888",
    status: "qualified",
    conversion_value: null,
    lead_score: 77,
    interest_tags: ["Plataforma de Pintura", "Fita Crepe Industrial"],
    origin: "campaign",
    created_at: daysAgo(3),
    pipeline_status: "transferido",
    ai_summary: "Empresa de manutenção predial. Precisa de plataforma de pintura articulada e fita crepe industrial em grande quantidade. Contrato mensal.",
    estimated_value: 8500,
    last_contact_at: daysAgo(1),
    conversation_id: null,
  },
  {
    id: "mock-cli-009",
    name: "Eduardo Ferreira Lima",
    phone: "5511909879999",
    status: "qualified",
    conversion_value: null,
    lead_score: 69,
    interest_tags: ["Escada Extensível", "Lixadeira de Parede"],
    origin: "whatsapp",
    created_at: daysAgo(3),
    pipeline_status: "transferido",
    ai_summary: "Pintor profissional precisa de escada extensível de alumínio e lixadeira para preparação de paredes em sobrado. Transferido para fechar prazo e preço.",
    estimated_value: 2400,
    last_contact_at: daysAgo(2),
    conversation_id: null,
  },
  {
    id: "mock-cli-010",
    name: "Luciana Mendes Costa",
    phone: "5511998760000",
    status: "qualified",
    conversion_value: null,
    lead_score: 90,
    interest_tags: ["Andaime Fachadeiro", "Pulverizador Airless", "Compressor para Pintura"],
    origin: "organic",
    created_at: daysAgo(4),
    pipeline_status: "orcamento_enviado",
    ai_summary: "Grande empreiteira de pintura. Orçamento enviado para andaime fachadeiro + pulverizador airless + compressor. Obra em edifício comercial de 15 andares. Aguardando aprovação do engenheiro responsável.",
    estimated_value: 22000,
    last_contact_at: daysAgo(1),
    conversation_id: null,
  },
  {
    id: "mock-cli-011",
    name: "Thiago Ribeiro Santos",
    phone: "5511997651111",
    status: "qualified",
    conversion_value: null,
    lead_score: 83,
    interest_tags: ["Pistola de Pintura", "Plataforma de Pintura"],
    origin: "whatsapp",
    created_at: daysAgo(4),
    pipeline_status: "orcamento_enviado",
    ai_summary: "Dono de empresa de acabamento. Orçamento enviado para pistola de pintura profissional e plataforma. Boa probabilidade de fechar.",
    estimated_value: 5600,
    last_contact_at: daysAgo(2),
    conversation_id: null,
  },
  {
    id: "mock-cli-012",
    name: "Camila Barbosa Souza",
    phone: "5511996542222",
    status: "converted",
    conversion_value: 28000,
    lead_score: 95,
    interest_tags: ["Andaime Fachadeiro", "Pulverizador Airless", "Lixadeira de Parede"],
    origin: "campaign",
    created_at: daysAgo(5),
    pipeline_status: "venda_confirmada",
    ai_summary: "Venda confirmada! Pacote completo para pintura de condomínio: andaime fachadeiro + pulverizador airless + lixadeira de parede. Contrato de 60 dias assinado.",
    estimated_value: 28000,
    last_contact_at: daysAgo(1),
    conversation_id: null,
  },
  {
    id: "mock-cli-013",
    name: "André Martins Filho",
    phone: "5511995433333",
    status: "converted",
    conversion_value: 14500,
    lead_score: 91,
    interest_tags: ["Compressor para Pintura", "Pistola de Pintura", "Fita Crepe Industrial"],
    origin: "whatsapp",
    created_at: daysAgo(6),
    pipeline_status: "venda_confirmada",
    ai_summary: "Contrato fechado para compressor, pistola de pintura e fita crepe industrial. Serviço de pintura em escola municipal. Entrega dos equipamentos agendada.",
    estimated_value: 14500,
    last_contact_at: daysAgo(2),
    conversation_id: null,
  },
  {
    id: "mock-cli-014",
    name: "Vanessa Rocha Lima",
    phone: "5511994324444",
    status: "lost",
    conversion_value: null,
    lead_score: 24,
    interest_tags: ["Rolo de Pintura Industrial"],
    origin: "organic",
    created_at: daysAgo(6),
    pipeline_status: "perdido",
    ai_summary: "Desistiu por conta do prazo de entrega. Precisava dos rolos industriais com urgência e optou por comprar no varejo.",
    estimated_value: 1200,
    last_contact_at: daysAgo(5),
    conversation_id: null,
  },
  {
    id: "mock-cli-015",
    name: "Felipe Cardoso Neto",
    phone: "5511993215555",
    status: "lost",
    conversion_value: null,
    lead_score: 19,
    interest_tags: ["Escada Extensível"],
    origin: "whatsapp",
    created_at: daysAgo(7),
    pipeline_status: "perdido",
    ai_summary: "Não respondeu após 3 tentativas de contato. Havia perguntado sobre escada extensível para pintura de telhado, mas sem retorno há 5 dias.",
    estimated_value: 900,
    last_contact_at: daysAgo(7),
    conversation_id: null,
  },
];
