/**
 * Mock leads for demo purposes (equipment rental theme).
 * Used as fallback when no real leads exist in the database.
 */

function daysAgo(days: number): string {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(Math.floor(Math.random() * 10) + 8, Math.floor(Math.random() * 60));
  return d.toISOString();
}

export const MOCK_LEADS = [
  {
    id: "mock-001",
    name: "Carlos Silva",
    phone: "5511987654321",
    status: "new",
    conversion_value: null,
    lead_score: 45,
    interest_tags: ["Retroescavadeira"],
    origin: "whatsapp",
    created_at: daysAgo(0),
    pipeline_status: "ia_atendendo",
    ai_summary: "Cliente perguntou sobre locação de retroescavadeira para obra residencial. Precisa por 15 dias.",
    estimated_value: 8500,
    last_contact_at: daysAgo(0),
    conversation_id: null,
  },
  {
    id: "mock-002",
    name: "Ana Oliveira",
    phone: "5511976543210",
    status: "new",
    conversion_value: null,
    lead_score: 62,
    interest_tags: ["Plataforma Elevatória", "Gerador"],
    origin: "organic",
    created_at: daysAgo(0),
    pipeline_status: "ia_atendendo",
    ai_summary: "Interessada em plataforma elevatória articulada e gerador 150kVA para manutenção industrial.",
    estimated_value: 15000,
    last_contact_at: daysAgo(0),
    conversation_id: null,
  },
  {
    id: "mock-003",
    name: "Roberto Santos",
    phone: "5511965432109",
    status: "new",
    conversion_value: null,
    lead_score: 38,
    interest_tags: ["Compactador"],
    origin: "whatsapp",
    created_at: daysAgo(1),
    pipeline_status: "ia_atendendo",
    ai_summary: "Pediu orçamento de compactador de solo para terraplanagem. Ainda avaliando opções.",
    estimated_value: 3200,
    last_contact_at: daysAgo(1),
    conversation_id: null,
  },
  {
    id: "mock-004",
    name: "Fernanda Costa",
    phone: "5511954321098",
    status: "new",
    conversion_value: null,
    lead_score: 55,
    interest_tags: ["Mini Escavadeira"],
    origin: "campaign",
    created_at: daysAgo(1),
    pipeline_status: "ia_atendendo",
    ai_summary: "Veio pela campanha do Instagram. Quer mini escavadeira para limpeza de terreno. Prazo de 10 dias.",
    estimated_value: 12000,
    last_contact_at: daysAgo(0),
    conversation_id: null,
  },
  {
    id: "mock-005",
    name: "Marcos Pereira",
    phone: "5511943210987",
    status: "qualified",
    conversion_value: null,
    lead_score: 72,
    interest_tags: ["Guindaste", "Caminhão Munck"],
    origin: "whatsapp",
    created_at: daysAgo(2),
    pipeline_status: "qualificado",
    ai_summary: "Construtora precisa de guindaste 30t e munck para obra comercial. Projeto de 3 meses. Decisor confirmado.",
    estimated_value: 22000,
    last_contact_at: daysAgo(1),
    conversation_id: null,
  },
  {
    id: "mock-006",
    name: "Juliana Lima",
    phone: "5511932109876",
    status: "qualified",
    conversion_value: null,
    lead_score: 68,
    interest_tags: ["Plataforma Elevatória"],
    origin: "organic",
    created_at: daysAgo(2),
    pipeline_status: "qualificado",
    ai_summary: "Empresa de manutenção predial. Precisa de plataforma tesoura 12m para fachada. Orçamento aprovado internamente.",
    estimated_value: 18500,
    last_contact_at: daysAgo(1),
    conversation_id: null,
  },
  {
    id: "mock-007",
    name: "Ricardo Almeida",
    phone: "5511921098765",
    status: "qualified",
    conversion_value: null,
    lead_score: 80,
    interest_tags: ["Retroescavadeira", "Rolo Compressor"],
    origin: "whatsapp",
    created_at: daysAgo(3),
    pipeline_status: "transferido",
    ai_summary: "Empreiteira com obra de pavimentação. Precisa de retro e rolo compressor por 45 dias. Valor alto, transferido para consultor.",
    estimated_value: 35000,
    last_contact_at: daysAgo(0),
    conversation_id: null,
  },
  {
    id: "mock-008",
    name: "Patricia Souza",
    phone: "5511910987654",
    status: "qualified",
    conversion_value: null,
    lead_score: 75,
    interest_tags: ["Empilhadeira", "Gerador"],
    origin: "campaign",
    created_at: daysAgo(3),
    pipeline_status: "transferido",
    ai_summary: "Galpão logístico precisa de empilhadeira 2.5t e gerador de emergência. Contrato mensal.",
    estimated_value: 28000,
    last_contact_at: daysAgo(1),
    conversation_id: null,
  },
  {
    id: "mock-009",
    name: "Eduardo Ferreira",
    phone: "5511909876543",
    status: "qualified",
    conversion_value: null,
    lead_score: 70,
    interest_tags: ["Betoneira"],
    origin: "whatsapp",
    created_at: daysAgo(3),
    pipeline_status: "transferido",
    ai_summary: "Pequena construtora precisa de betoneira 400L para obra residencial. Transferido para fechar prazo e preço.",
    estimated_value: 9800,
    last_contact_at: daysAgo(2),
    conversation_id: null,
  },
  {
    id: "mock-010",
    name: "Luciana Mendes",
    phone: "5511998765432",
    status: "qualified",
    conversion_value: null,
    lead_score: 88,
    interest_tags: ["Guindaste", "Plataforma Elevatória"],
    origin: "organic",
    created_at: daysAgo(4),
    pipeline_status: "orcamento_enviado",
    ai_summary: "Grande construtora. Orçamento enviado para guindaste 50t + plataforma articulada 20m. Aguardando aprovação do diretor.",
    estimated_value: 42000,
    last_contact_at: daysAgo(1),
    conversation_id: null,
  },
  {
    id: "mock-011",
    name: "Thiago Ribeiro",
    phone: "5511997654321",
    status: "qualified",
    conversion_value: null,
    lead_score: 82,
    interest_tags: ["Retroescavadeira"],
    origin: "whatsapp",
    created_at: daysAgo(4),
    pipeline_status: "orcamento_enviado",
    ai_summary: "Fazendeiro precisa de retro para abertura de estrada rural. Orçamento de 30 dias enviado. Boa probabilidade de fechar.",
    estimated_value: 25000,
    last_contact_at: daysAgo(2),
    conversation_id: null,
  },
  {
    id: "mock-012",
    name: "Camila Barbosa",
    phone: "5511996543210",
    status: "converted",
    conversion_value: 45000,
    lead_score: 95,
    interest_tags: ["Mini Escavadeira", "Compactador", "Gerador"],
    origin: "campaign",
    created_at: daysAgo(5),
    pipeline_status: "venda_confirmada",
    ai_summary: "Venda confirmada! Pacote completo para loteamento: mini escavadeira + compactador + gerador. Contrato de 60 dias assinado.",
    estimated_value: 45000,
    last_contact_at: daysAgo(1),
    conversation_id: null,
  },
  {
    id: "mock-013",
    name: "Andre Martins",
    phone: "5511995432109",
    status: "converted",
    conversion_value: 32000,
    lead_score: 90,
    interest_tags: ["Rolo Compressor", "Caminhão Munck"],
    origin: "whatsapp",
    created_at: daysAgo(6),
    pipeline_status: "venda_confirmada",
    ai_summary: "Contrato fechado para rolo compressor e munck. Obra de pavimentação em condomínio. Entrega agendada.",
    estimated_value: 32000,
    last_contact_at: daysAgo(2),
    conversation_id: null,
  },
  {
    id: "mock-014",
    name: "Vanessa Rocha",
    phone: "5511994321098",
    status: "lost",
    conversion_value: null,
    lead_score: 25,
    interest_tags: ["Betoneira"],
    origin: "organic",
    created_at: daysAgo(6),
    pipeline_status: "perdido",
    ai_summary: "Desistiu por conta do preço. Optou por comprar betoneira própria. Não tem interesse em locação no momento.",
    estimated_value: 5000,
    last_contact_at: daysAgo(5),
    conversation_id: null,
  },
  {
    id: "mock-015",
    name: "Felipe Cardoso",
    phone: "5511993210987",
    status: "lost",
    conversion_value: null,
    lead_score: 20,
    interest_tags: ["Compactador"],
    origin: "whatsapp",
    created_at: daysAgo(7),
    pipeline_status: "perdido",
    ai_summary: "Não respondeu após 3 tentativas de contato. Sem retorno há 5 dias.",
    estimated_value: 2800,
    last_contact_at: daysAgo(7),
    conversation_id: null,
  },
];
